using AC_BM.Models;

namespace AC_BM.Helper
{
    public static class Countries
    {
        public static List<Country> GetAll()
        {
            return new List<Country>
            {
                new Country() { Name = "Afghanistan", Id = "AF" },
                new Country() { Name = "Albania", Id = "AL" },
                new Country() { Name = "Algeria", Id = "	DZ" },
                new Country() { Name = "American Samoa", Id = "AS	" },
                new Country() { Name = "Andorra", Id = "	AD" },
                new Country() { Name = "Angola", Id = "	AO" },
                new Country() { Name = "Anguilla", Id = "	AI" },
                new Country() { Name = "Antarctica", Id = "AQ" },
                new Country() { Name = "Antigua and Barbuda", Id = "AG" },
                new Country() { Name = "Argentina", Id = "AR" },
                new Country() { Name = "Armenia", Id = "	AM" },
                new Country() { Name = "Aruba", Id = "	AW" },
                new Country() { Name = "Australia", Id = "	AU" },
                new Country() { Name = "Austria", Id = "	AT" },
                new Country() { Name = "Azerbaijan", Id = "	AZ	" },
                new Country() { Name = "Bahamas", Id = " BS" },
                new Country() { Name = "Bahrain", Id = "	BH	" },
                new Country() { Name = "Bangladesh", Id = "	BD	" },
                new Country() { Name = "Barbados", Id = "	BB	" },
                new Country() { Name = "Belarus", Id = "	BY	" },
                new Country() { Name = "Belgium", Id = "	BE	" },
                new Country() { Name = "Belize", Id = "	BZ	" },
                new Country() { Name = "Benin", Id = "	BJ	" },
                new Country() { Name = "Bermuda", Id = "	BM	" },
                new Country() { Name = "Bhutan", Id = "	BT	" },
                new Country() { Name = "Bolivia (Plurinational State of)", Id = "BO" },
                new Country() { Name = "Bonaire, Sint Eustatius and Saba", Id = "BQ" },
                new Country() { Name = "Bosnia and Herzegovina", Id = "	BA" },
                new Country() { Name = "Botswana", Id = "	BW	" },
                new Country() { Name = "Bouvet Island", Id = "	BV	" },
                new Country() { Name = "Brazil", Id = "	BR	" },
                new Country() { Name = "British Indian Ocean Territory", Id = "IO	" },
                new Country() { Name = "Brunei Darussalam", Id = "	BN" },
                new Country() { Name = "Bulgaria", Id = "	BG	" },
                new Country() { Name = "Burkina Faso", Id = "	BF	" },
                new Country() { Name = "Burundi", Id = "	BI	" },
                new Country() { Name = "Cabo Verde", Id = "	CV	" },
                new Country() { Name = "Cambodia", Id = "	KH	" },
                new Country() { Name = "Cameroon", Id = "	CM	" },
                new Country() { Name = "Canada", Id = "	CA	" },
                new Country() { Name = "Cayman Islands", Id = "	KY" },
                new Country() { Name = "Central African Republic", Id = "	CF	" },
                new Country() { Name = "Chad", Id = "	TD	" },
                new Country() { Name = "Chile", Id = "	CL	" },
                new Country() { Name = "China", Id = "	CN	" },
                new Country() { Name = "Christmas Island", Id = "	CX" },
                new Country() { Name = "Cocos (Keeling) Islands", Id = "	CC" },
                new Country() { Name = "Colombia", Id = "	CO	" },
                new Country() { Name = "Comoros", Id = "	KM	" },
                new Country() { Name = "Congo (the Democratic Republic)", Id = "	CD	" },
                new Country() { Name = "Congo", Id = " 	CG	" },
                new Country() { Name = "Cook Islands", Id = "	CK	" },
                new Country() { Name = "Costa Rica", Id = "	CR	" },
                new Country() { Name = "Croatia", Id = "	HR	" },
                new Country() { Name = "Cuba", Id = "	CU	" },
                new Country() { Name = "Curaçao", Id = "	CW	" },
                new Country() { Name = "Cyprus", Id = "	CY	" },
                new Country() { Name = "Czechia", Id = "	CZ	" },
                new Country() { Name = "Côte d'Ivoire", Id = "	CI" },
                new Country() { Name = "Denmark", Id = "	DK	" },
                new Country() { Name = "Djibouti", Id = "	DJ	" },
                new Country() { Name = "Dominica", Id = "	DM	" },
                new Country() { Name = "Dominican Republic", Id = "	DO	" },
                new Country() { Name = "Ecuador", Id = "	EC	" },
                new Country() { Name = "Egypt", Id = "	EG	" },
                new Country() { Name = "El Salvador", Id = "	SV	" },
                new Country() { Name = "Equatorial Guinea", Id = "	GQ" },
                new Country() { Name = "Eritrea", Id = "	ER	" },
                new Country() { Name = "Estonia", Id = "	EE	" },
                new Country() { Name = "Eswatini",  Id = "	SZ	" },
                new Country() { Name = "Ethiopia", Id = "	ET	" },
                new Country() { Name = "Falkland Islands", Id = "	FK	" },
                new Country() { Name = "Faroe Islands", Id = "	FO	" },
                new Country() { Name = "Fiji", Id = "	FJ	" },
                new Country() { Name = "Finland", Id = "	FI	" },
                new Country() { Name = "France", Id = "	FR	" },
                new Country() { Name = "French Guiana", Id = "	GF	" },
                new Country() { Name = "French Polynesia", Id = "	PF	" },
                new Country() { Name = "French Southern Territories", Id = "	TF" },
                new Country() { Name = "Gabon", Id = "	GA	" },
                new Country() { Name = "Gambia", Id = " 	GM	" },
                new Country() { Name = "Georgia", Id = "	GE	" },
                new Country() { Name = "Germany", Id = "	DE	" },
                    new Country() { Name = "Ghana", Id = "	GH	" },
                    new Country() { Name = "Gibraltar", Id = "	GI	" },
                    new Country() { Name = "Greece", Id = "	GR	" },
                    new Country() { Name = "Greenland", Id = "	GL	" },
                    new Country() { Name = "Grenada", Id = "	GD	" },
                    new Country() { Name = "Guadeloupe", Id = "	GP	" },
                    new Country() { Name = "Guam", Id = "	GU	" },
                    new Country() { Name = "Guatemala", Id = "	GT	" },
                    new Country() { Name = "Guernsey", Id = "	GG	" },
                    new Country() { Name = "Guinea", Id = "	GN	" },
                    new Country() { Name = "Guinea-Bissau", Id = "	GW	" },
                    new Country() { Name = "Guyana", Id = "	GY	" },
                    new Country() { Name = "Haiti", Id = "	HT	" },
                    new Country() { Name = "Heard Island and McDonald Islands", Id = "	HM	" },
                    new Country() { Name = "Holy See (the)", Id = "	VA	" },
                    new Country() { Name = "Honduras", Id = "	HN	" },
                    new Country() { Name = "Hong Kong", Id = "	HK	" },
                    new Country() { Name = "Hungary", Id = "	HU	" },
                    new Country() { Name = "Iceland", Id = "	IS	" },
                    new Country() { Name = "India", Id = "	IN	" },
                    new Country() { Name = "Indonesia", Id = "	ID	" },
                    new Country() { Name = "Iran ", Id = "	IR	" },
                    new Country() { Name = "Iraq", Id = "	IQ	" },
                    new Country() { Name = "Ireland", Id = "	IE	" },
                    new Country() { Name = "Isle of Man", Id = "	IM	" },
                    new Country() { Name = "Israel", Id = "	IL	" },
                    new Country() { Name = "Italy", Id = "  IT	" },
                    new Country() { Name = "Jamaica", Id = "	JM	" },
                    new Country() { Name = "Japan", Id = "	JP	" },
                    new Country() { Name = "Jersey", Id = "	JE	" },
                    new Country() { Name = "Jordan", Id = " 	JO	" },
                    new Country() { Name = "Kazakhstan", Id = "	KZ	" },
                    new Country() { Name = "Kenya", Id = "	KE	" },
                    new Country() { Name = "Kiribati", Id = "	KI	" },
                    new Country() { Name = "Korea (the Democratic People's Republic)", Id = "	KP	" },
                    new Country() { Name = "Korea", Id = "	KR	" },
                    new Country() { Name = "Kuwait", Id = "	KW	" },
                    new Country() { Name = "Kyrgyzstan	", Id = "KG	" },
                    new Country() { Name = "Lao People's Democratic Republic", Id = " 	LA	" },
                    new Country() { Name = "Latvia", Id = "	LV	" },
                    new Country() { Name = "Lebanon", Id = "	LB	" },
                    new Country() { Name = "Lesotho", Id = "	LS	" },
                    new Country() { Name = "Liberia", Id = "	LR	" },
                    new Country() { Name = "Libya", Id = "	LY	" },
                    new Country() { Name = "Liechtenstein", Id = "	LI	" },
                    new Country() { Name = "Lithuania", Id = "	LT	" },
                    new Country() { Name = "Luxembourg", Id = "	LU	" },
                    new Country() { Name = "Macao", Id = "	MO	" },
                    new Country() { Name = "Madagascar", Id = "	MG	" },
                    new Country() { Name = "Malawi", Id = "	MW	" },
                    new Country() { Name = "Malaysia", Id = "	MY	" },
                    new Country() { Name = "Maldives", Id = "	MV	" },
                    new Country() { Name = "Mali", Id = "	ML	" },
                    new Country() { Name = "Malta", Id = "	MT	" },
                    new Country() { Name = "Marshall Islands", Id = "	MH	" },
                    new Country() { Name = "Martinique", Id = "	MQ	" },
                    new Country() { Name = "Mauritania", Id = "	MR	" },
                    new Country() { Name = "Mauritius", Id = "	MU	" },
                    new Country() { Name = "Mayotte", Id = "	YT	" },
                    new Country() { Name = "Mexico", Id = "	MX	" },
                    new Country() { Name = "Micronesia", Id = "	FM	" },
                    new Country() { Name = "Moldova", Id = "	MD	" },
                    new Country() { Name = "Monaco", Id = "	MC	" },
                    new Country() { Name = "Mongolia", Id = "	MN	" },
                    new Country() { Name = "Montenegro", Id = "	ME	" },
                    new Country() { Name = "Montserrat", Id = "	MS	" },
                    new Country() { Name = "Morocco", Id = "	MA	" },
                    new Country() { Name = "Mozambique", Id = "	MZ	" },
                    new Country() { Name = "Myanmar", Id = "	MM	" },
                    new Country() { Name = "Namibia", Id = "	NA	" },
                    new Country() { Name = "Nauru", Id = "	NR	" },
                    new Country() { Name = "Nepal", Id = "	NP	" },
                    new Country() { Name = "Netherlands", Id = "	NL	" },
                    new Country() { Name = "New Caledonia", Id = "	NC	" },
                    new Country() { Name = "New Zealand", Id = "	NZ" },
                    new Country() { Name = "Nicaragua", Id = "	NI" },
                    new Country() { Name = "Niger", Id = "	NE	" },
                    new Country() { Name = "Nigeria", Id = "	NG	" },
                    new Country() { Name = "Niue", Id = "	NU	" },
                    new Country() { Name = "Norfolk Island", Id = "	NF	" },
                    new Country() { Name = "Northern Mariana Islands", Id = "	MP	" },
                    new Country() { Name = "Norway", Id = "	NO	" },
                    new Country() { Name = "Oman", Id = "	OM	" },
                    new Country() { Name = "Pakistan", Id = "	PK	" },
                    new Country() { Name = "Palau", Id = "	PW	" },
                    new Country() { Name = "Palau", Id = "	PW	" },
                    new Country() { Name = "Palau", Id = "	PW	" },
                    new Country() { Name = "Palestine", Id = "	PS	" },
                    new Country() { Name = "Panama", Id = "	PA	" },
                    new Country() { Name = "Papua New Guinea", Id = "	PG	" },
                    new Country() { Name = "Paraguay", Id = "	PY	" },
                    new Country() { Name = "Peru", Id = "	PE	" },
                    new Country() { Name = "Philippines", Id = "	PH	" },
                    new Country() { Name = "Pitcairn", Id = "	PN	" },
                    new Country() { Name = "Poland", Id = "	PL	" },
                    new Country() { Name = "Portugal", Id = "	PT	" },
                    new Country() { Name = "Puerto Rico", Id = "	PR	" },
                    new Country() { Name = "Qatar", Id = "	QA	" },
                    new Country() { Name = "Republic of North Macedonia", Id = "	MK	" },
                    new Country() { Name = "Romania", Id = "	RO	" },
                    new Country() { Name = "Russian Federation", Id = "	RU	" },
                    new Country() { Name = "Rwanda", Id = "	RW	" },
                    new Country() { Name = "Réunion", Id = "	RE" },
                    new Country() { Name = "Saint Barthélemy", Id = "	BL	" },
                    new Country() { Name = "Saint Helena "    ,Id="    SH  "},
                     new Country() { Name = "Saint Kitts and Nevis", Id = "	KN	" },
                        new Country() { Name = "Saint Lucia", Id = "	LC	" },
                        new Country() { Name = "Saint Martin", Id = "	MF	" },
                        new Country() { Name = "Saint Pierre and Miquelon", Id = "	PM	" },
                        new Country() { Name = "Saint Vincent and the Grenadines", Id = "	VC	" },
                        new Country() { Name = "Samoa", Id = "	WS	" },
                        new Country() { Name = "San Marino", Id = "	SM	" },
                        new Country() { Name = "Sao Tome and Principe", Id = "	ST	" },
                        new Country() { Name = "Saudi Arabia", Id = "	SA	" },
                        new Country() { Name = "Senegal", Id = "	SN	" },
                        new Country() { Name = "Serbia", Id = "	RS	" },
                        new Country() { Name = "Seychelles", Id = "	SC	" },
                        new Country() { Name = "Sierra Leone", Id = "	SL	" },
                        new Country() { Name = "Singapore", Id = "	SG	" },
                        new Country() { Name = "Sint Maarten", Id = "	SX	" },
                        new Country() { Name = "Slovakia", Id = "	SK	" },
                        new Country() { Name = "Slovenia", Id = "	SI	" },
                        new Country() { Name = "Solomon Islands", Id = "	SB	" },
                        new Country() { Name = "Somalia", Id = "	SO	" },
                        new Country() { Name = "South Africa", Id = "	ZA	" },
                        new Country() { Name = "South Georgia and the South Sandwich Islands", Id = "GS	" },
                        new Country() { Name = "South Sudan", Id = "	SS	" },
                        new Country() { Name = "Spain", Id = "	ES	" },
                        new Country() { Name = "Sri Lanka", Id = "	LK	" }, 
                        new Country() { Name = "Sudan", Id = "	SD	" },
                        new Country() { Name = "Suriname", Id = "	SR	" },
                        new Country() { Name = "Svalbard and Jan Mayen", Id = "	SJ	" },
                        new Country() { Name = "Sweden", Id = "	SE	" },
                        new Country() { Name = "Switzerland", Id = "	CH	" },
                        new Country() { Name = "Syrian Arab Republic", Id = "	SY	" },
                        new Country() { Name = "Taiwan", Id = "	TW	" },
                        new Country() { Name = "Tajikistan", Id = "	TJ	" },
                        new Country() { Name = "Tanzania ", Id = "	TZ	" },
                        new Country() { Name = "Thailand", Id = "	TH	" },
                        new Country() { Name = "Timor-Leste", Id = "	TL	" },
                        new Country() { Name = "Togo", Id = "	TG	" },
                        new Country() { Name = "Tokelau", Id = "	TK	" },
                        new Country() { Name = "Tonga", Id = "	TO	" },
                        new Country() { Name = "Trinidad and Tobago", Id = "	TT	" },
                        new Country() { Name = "Tunisia", Id = "	TN	" },
                        new Country() { Name = "Turkey", Id = "	TR	" },
                        new Country() { Name = "Turkmenistan", Id = "	TM	" },
                        new Country() { Name = "Turks and Caicos Islands", Id = "	TC	" },
                        new Country() { Name = "Tuvalu", Id = "	TV	" },
                        new Country() { Name = "Uganda", Id = "	UG	" },
                        new Country() { Name = "Ukraine", Id = "	UA	" },
                        new Country() { Name = "United Arab Emirates", Id = "	AE	" },
                        new Country() { Name = "United Kingdom of Great Britain and Northern Ireland", Id = "GB	" },
                        new Country() { Name = "United States Minor Outlying Islands", Id = "	UM	" },
                        new Country() { Name = "United States of America", Id = "	US	" },
                        new Country() { Name = "Uruguay", Id = "  UY  " },
                        new Country() { Name = "Uzbekistan", Id = "UZ" },
                        new Country() { Name = "Vanuatu", Id = "VU	" },
                        new Country() { Name = "Venezuela", Id = "VE" },
                        new Country() { Name = "Viet Nam", Id = "VN" },
                        new Country() { Name = "Virgin Islands (British)", Id = "VG" },
                        new Country() { Name = "Virgin Islands (U.S.)", Id = "VI" },
                        new Country() { Name = "Wallis and Futuna", Id = "WF" },
                        new Country() { Name = "Western Sahara", Id = "EH" },
                        new Country() { Name = "Yemen", Id = "YE" },
                        new Country() { Name = "Zambia", Id = "ZM" },
                        new Country() { Name = "Zimbabwe", Id = "ZW" },
                        new Country() { Name = "Åland Islands", Id = "AX" },   
            };
        }
    }
}
